### ISSUE TITLE
如果同时存在url变量和json实体，怎么玩？？

### ISSUE THREAD

**Issue by wencan** [ssgo/s#7]
目前，从我了解到的情况，无论查询参数、表单参数、其它实体内容，都被放到in struct中。假如那几项同时需要，怎么玩？？

假如有下面的请求：
```
POST /api/users/123 HTTP/1.1
Host: 127.0.0.1:14176
Content-Type: application/json
Cache-Control: no-cache

{
	"name": "wencan",
	"age": 18
}
```
需要获取到url中的123，还需要获取到json实体，怎么玩？？

**Comment by darryhold** [comment]
举例如下
type user struct {
	Name string
	Ag   string
	Idd  string
}
func showUser(in user, req *http.Request) (out user) {
	fmt.Println("in", in)
	out.Idd = in.Idd
	out.Name = in.Name
	out.Ag = in.Ag
	return
}

func main() {
……
s.Restful(1, "POST", "/user/{id}", showUser)
……
}
