### ISSUE TITLE
没有处理错误

### ISSUE THREAD

**Issue by wencan** [ssgo/s#9]
添加下面的处理：
```
	s.Restful(0, http.MethodGet, "/api/hello", func(w http.ResponseWriter, r *http.Request) {
		panic(errors.New("Test"))
	})
```

调用结果：
![image](https://user-images.githubusercontent.com/1072917/48760471-fad6a300-ece0-11e8-8c18-174c529c1c09.png)

**Comment by darryhold** [comment]
后续考虑在框架底层来处理
